CREATE DATABASE COLLEGE_01;
USE COLLEGE_01;

CREATE TABLE DEPARTMENT (
DEPT_ID INT PRIMARY KEY auto_increment,
DEPT_NAME VARCHAR(100) UNIQUE NOT NULL); -- DEPARTMENT TABLE

CREATE TABLE STUDENT (
STUDENT_ID INT PRIMARY KEY auto_increment,
NAME VARCHAR (100),
EMAIL VARCHAR(100) UNIQUE,
PHONE VARCHAR(15),
GENDER ENUM ('MALE','FEMALE','OTHER'),
DOB DATE,
DEPT_ID INT,
ADMISSION_DATE DATE DEFAULT (CURRENT_DATE),
FOREIGN KEY(DEPT_ID) references DEPARTMENT(DEPT_ID)); -- STUDENT TABLE

CREATE TABLE FACULTY(
FACULTY_ID INT PRIMARY KEY auto_increment,
NAME VARCHAR(100),
EMAIL VARCHAR(100),
SALARY DECIMAL(10,2),
DEPT_ID INT,
FOREIGN KEY (DEPT_ID) references DEPARTMENT(DEPT_ID));  -- FACULTY TABLE

CREATE TABLE COURSE (
COURSE_ID INT PRIMARY KEY auto_increment,
COURSE_NAME VARCHAR(100),
CREDITS INT,
DEPT_ID INT,
FACULTY_ID INT,
FOREIGN KEY (DEPT_ID) references DEPARTMENT(DEPT_ID),
foreign key (FACULTY_ID) references FACULTY(FACULTY_ID)); -- COURSE TABLE

CREATE TABLE ENROLLMENT (
ENROLL_ID INT PRIMARY KEY auto_increment,
STUDENT_ID INT,
COURSE_ID INT,
ENROLL_DATE DATE DEFAULT (CURRENT_DATE),
UNIQUE(STUDENT_ID,COURSE_ID),
foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),
foreign key (COURSE_ID) references COURSE(COURSE_ID));  -- ENROLLMENT TABLE

CREATE TABLE ATTENDANCE(
ATTENDANCE_ID INT PRIMARY KEY auto_increment,
STUDENT_ID INT,
COURSE_ID INT,
DATE DATE,
STATUS ENUM ('PRESENT','ABSENT'),
foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),
foreign key (COURSE_ID) references COURSE(COURSE_ID));  -- ATTENDANCE TABLE
 
CREATE TABLE MARKS (
MARKS_ID INT PRIMARY KEY auto_increment,
STUDENT_ID INT,
COURSE_ID INT,
MARKS INT CHECK (MARKS BETWEEN 0 AND 100),
foreign key (STUDENT_ID) references STUDENT(STUDENT_ID),
foreign key (COURSE_ID) references COURSE (COURSE_ID));  -- MARKS TABLE

CREATE TABLE FEES (
FEE_ID INT PRIMARY KEY auto_increment,
STUDENT_ID INT,
TOTAL_FEE decimal(10,2),
PAID_AMOUNT decimal(10,2),
foreign key (STUDENT_ID) references STUDENT(STUDENT_ID)); -- FEES TABLE

-- FIRST WE CREATE ALL TABLES WHICH IS REQUIRED FOR THE PROJECT THAN WE CAN INSERT DATA IN THE TABLE 
INSERT INTO DEPARTMENT (DEPT_NAME)
VALUES ('COMPUTER SCIENCE'),('MECHANICAL'),('CIVIL'),('POLITICAL SCIENCE');
SELECT * FROM DEPARTMENT;

INSERT INTO STUDENT (NAME,EMAIL,PHONE,GENDER,DOB,DEPT_ID)
VALUES 
('RAHUL SHARMA','RAHUL@GMAIL.COM','9876543210','MALE','2002-05-10',1),
('ANITA VERMA' ,'ANITA@GAMIL.COM','9876543211','FEMALE','2003-03-12',2),
('AYUSHMAAN' ,'AYUSHMAAN@GMAIL.COM','7999670900','MALE','2002-01-18',4),
('MAYA','MAYA@GMAIL.COM','7767677833','FEMALE','2000-01-19',3),
 ('SEEYA','SEEYA@GMAIL.COM','6389145890','FEMALE','2000-09-12',4);
 SELECT * FROM STUDENT;

INSERT INTO FACULTY (NAME,EMAIL,SALARY,DEPT_ID)
VALUES
('DR SINGH','SINGH@GMAIL.COM',80000,1),
('PROF KUMAR','KUMAR@GMAIL.COM',75000,2),
('RAJEEV SIR','RAJEEV@GMAIL.COM',90000,3),
('DR RAVI','RAVI@GMAIL.COM',85000,4);
SELECT * FROM FACULTY;

INSERT INTO COURSE (COURSE_NAME,CREDITS,DEPT_ID,FACULTY_ID)
VALUES
('DATA ANALYTICS',5,1,1),
('THERMODYNAMICS',3,2,2),
('DATA SCIENCE',4,3,3),
('HISTORY',4,4,4);
SELECT * FROM COURSE;

 INSERT INTO ENROLLMENT (ENROLL_ID,STUDENT_ID,COURSE_ID,ENROLL_DATE)
 VALUES
 (1,1,1,'2024-09-12'),
 (2,2,2,'2024-08-13'),
 (3,3,3,'2024-09-12'),
 (4,4,4,'2024-08-13');
 SELECT * FROM ENROLLMENT;
 
  INSERT INTO ATTENDANCE (STUDENT_ID,COURSE_ID,STATUS,DATE)
 VALUES
 (1,1,'PRESENT','2026-12-30'),
 (2,2,'ABSENT','2026-12-30'),
 (3,3,'PRESENT','2026-12-30'),
 (4,4,'ABSENT','2026-12-30');
SELECT * FROM ATTENDANCE;
 
 INSERT INTO MARKS (STUDENT_ID,COURSE_ID,MARKS)
 VALUES
 (1,1,97),
 (2,2,75),
 (3,3,65),
 (4,4,40);
 SELECT * FROM MARKS;
 
 INSERT INTO FEES (STUDENT_ID,TOTAL_FEE,PAID_AMOUNT)
 VALUES
 (1,2000.55,2000.55),
 (2,2000.55,1500.55),
 (3,2000.55,1000.55),
 (4,2000.55,2200.55);
 SELECT * FROM FEES;
 
 -- GRADE CALCULATION DYNAMIC
SELECT
S.NAME,
C.COURSE_NAME,
M.MARKS,
CASE
 WHEN M.MARKS >= 90 THEN 'A+'
 WHEN M.mARKS >= 75 THEN 'A'
 WHEN M.MARKS >= 60 THEN 'B'
 WHEN M.MARKS >= 50 THEN 'C'
 ELSE 'F'
END AS GRADE
FROM MARKS m
JOIN STUDENT S ON M.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C ON M.COURSE_ID = C.COURSE_ID;

-- FEE STATUS DYNAMIC
SELECT 
S.NAME,
F.TOTAL_FEE,
F.PAID_AMOUNT,
(F.TOTAL_FEE - F.PAID_AMOUNT) AS DUE_AMOUNT,
CASE
 WHEN(F.TOTAL_FEE - F.PAID_AMOUNT) = 0 THEN 'PAID'
 ELSE 'PENDING'
END AS STATUS 
FROM FEES f
JOIN STUDENT S ON F.STUDENT_ID = S.STUDENT_ID;

-- ATTENDANCE PERCENTAGE

SELECT 
S.NAME,
C.COURSE_NAME,
ROUND(SUM(A.STATUS='PRESENT')*100/COUNT(*),2) AS ATTENDANCE_PERCENTAGE
FROM ATTENDANCE A 
JOIN STUDENT S ON A.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C ON A.COURSE_ID = C.COURSE_ID
group by S.NAME,C.COURSE_NAME;

-- TOPPER PER COURSE
SELECT
C.COURSE_NAME,
S.NAME,
M.MARKS
FROM MARKS M 
JOIN STUDENT S ON M.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C ON M.COURSE_ID = C.COURSE_ID
WHERE (C.COURSE_ID,M.MARKS) IN (
 SELECT COURSE_ID,MAX(MARKS)
 FROM MARKS
 GROUP BY COURSE_ID);
 
 -- LOW ATTENDENCE STUDENTS
 SELECT * FROM (
  SELECT
  S.NAME,
  ROUND(SUM(A.STATUS='PRESENT')*100/COUNT(*),2) AS PERCENTAGE
  FROM ATTENDANCE A 
  JOIN STUDENT S ON A.STUDENT_ID = S.STUDENT_ID
  group by S.NAME)
  AS TEMP
  WHERE PERCENTAGE < 75;
  
  -- FEE DEFAULTER
SELECT
  S.NAME,
  (F.TOTAL_FEE - F.PAID_AMOUNT) AS DUE_AMOUNT
  FROM FEES f
  JOIN STUDENT S ON F.STUDENT_ID = S.STUDENT_ID
  WHERE (F.TOTAL_FEE - F.PAID_AMOUNT) > 0;
  
  -- REPORT CARD VIEW 
CREATE VIEW REPORT_CARD AS
 SELECT
 S.NAME,
 C.COURSE_NAME,
 M.MARKS,
  CASE
  WHEN M.MARKS >= 90 THEN 'A+'
  WHEN M.MARKS >= 75 THEN 'A'
  WHEN M.MARKS >= 60 THEN 'B'
  WHEN M.MARKS >= 50 THEN 'C'
  ELSE 'F'
END AS GRADE
FROM MARKS m
JOIN STUDENT S ON M.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C ON M.COURSE_ID = C.COURSE_ID;
SELECT * FROM REPORT_CARD;

-- STORED PROCEDURE
DELIMITER $$
CREATE PROCEDURE GET_STUDENTREPORT(IN ISD INT)
BEGIN
 SELECT * FROM REPORT_CARD
 WHERE NAME = (SELECT NAME FROM STUDENT WHERE STUDENT_ID = ISD);
END $$
DELIMITER ;
CALL GET_STUDENTREPORT(2);

SHOW FULL TABLES;